// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated. Do not modify by hand.
 *
 * Args:
 *     state: Matrix21
 *     u: Matrix11
 *
 * Outputs:
 *     state_dot: Matrix21
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 2, 1> DoubleIntegratorDiscreteTimeDynamics(
    const Eigen::Matrix<Scalar, 2, 1>& state, const Eigen::Matrix<Scalar, 1, 1>& u) {
  // Total ops: 0

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  Eigen::Matrix<Scalar, 2, 1> _state_dot;

  _state_dot(0, 0) = state(1, 0);
  _state_dot(1, 0) = u(0, 0);

  return _state_dot;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
